(function(){
'use strict';
const state={catalog:{movies:[],shows:[]},focus:0,focusables:[],heroItem:null,mode:'home',current:null,player:null,saveTimer:null};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const API_BASE=(location.protocol==='http:'||location.protocol==='https:')?'':(window.HOME_CINEMA_API||'');
const api=async(path,opts)=>{const r=await fetch(API_BASE+path,opts);if(!r.ok)throw new Error(await r.text());return r.json()};
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2500)}
function card(item,type){const title=item.title||'Без названия';const img=item.poster_url||'';const meta=type==='show'?`${item.season_count||0} сез. • ${item.episode_count||0} сер.`:(item.year||'Фильм');return `<div class="card focusable" tabindex="0" data-type="${type}" data-id="${item.id}"><div class="poster" ${img?`style="background-image:url('${esc(img)}')"`:''}><span class="badge">${type==='show'?'СЕРИАЛ':'ФИЛЬМ'}</span></div><div class="card-title">${esc(title)}</div><div class="card-meta">${esc(meta)}</div></div>`}
function rebuildFocus(){state.focusables=$$('.focusable:not(.hidden)');if(state.focus>=state.focusables.length)state.focus=0;state.focusables.forEach(x=>x.classList.remove('focused'));if(state.focusables[state.focus]){state.focusables[state.focus].classList.add('focused');state.focusables[state.focus].scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'})}}
function setHero(item){if(!item)return;state.heroItem=item;$('#heroTitle').textContent=item.title||'Домашний кинотеатр';$('#heroMeta').textContent=[item.year,item.rating?`★ ${Number(item.rating).toFixed(1)}`:null,item.genres].filter(Boolean).join(' • ');$('#heroOverview').textContent=item.overview||'Описание будет добавлено после сопоставления с TMDb.';if(item.backdrop_url)$('#hero').style.backgroundImage=`url('${item.backdrop_url}')`}
async function load(){try{state.catalog=await api('/api/catalog');$('#movieRow').innerHTML=state.catalog.movies.map(x=>card(x,'movie')).join('');$('#showRow').innerHTML=state.catalog.shows.map(x=>card(x,'show')).join('');const first=state.catalog.movies[0]||state.catalog.shows[0];setHero(first);$('#empty').classList.toggle('hidden',!!first);wireCards();rebuildFocus()}catch(e){toast('Сервер каталога недоступен');console.error(e)}}
function wireCards(){const scan=$('#scanButton');if(scan)scan.onclick=async()=>{toast('Сканирование запущено…');try{const r=await api('/api/scan',{method:'POST'});toast(`Найдено: ${r.movies} фильмов, ${r.shows} сериалов, ${r.episodes} серий`);await load()}catch(e){toast('Не удалось просканировать медиатеку')}};$$('.card').forEach(el=>el.addEventListener('click',()=>openDetails(el.dataset.type,Number(el.dataset.id))));$('#heroPlay').onclick=()=>{if(state.heroItem){if(state.heroItem.source_url)play(state.heroItem.source_url,state.heroItem.title);else openDetails('show',state.heroItem.id)}}}
async function openDetails(type,id){let item=await api(type==='movie'?`/api/movies/${id}`:`/api/shows/${id}`);state.mode='details';state.current=item;const eps=type==='show'?`<div class="episodes"><h2>Серии</h2>${item.episodes.map(e=>`<div class="episode focusable" data-source="${esc(e.source_url)}" data-title="${esc(e.title||`Серия ${e.episode}`)}">S${String(e.season).padStart(2,'0')}E${String(e.episode).padStart(2,'0')} — ${esc(e.title||`Серия ${e.episode}`)}</div>`).join('')}</div>`:'';$('#details').innerHTML=`${item.backdrop_url?`<div class="details-bg" style="background-image:url('${esc(item.backdrop_url)}')"></div>`:''}<div class="details-shade"></div><div class="details-content"><div class="eyebrow">${type==='show'?'СЕРИАЛ':'ФИЛЬМ'}</div><h1>${esc(item.title)}</h1><div class="hero-meta">${[item.year,item.rating?`★ ${Number(item.rating).toFixed(1)}`:null,item.genres].filter(Boolean).join(' • ')}</div><p>${esc(item.overview||'Описание будет добавлено после сопоставления с TMDb.')}</p><div class="details-buttons">${type==='movie'?`<button class="focusable primary" data-source="${esc(item.source_url)}" data-title="${esc(item.title)}">▶ Смотреть</button>`:''}<button class="focusable" data-back="1">Назад</button></div></div>${eps}`;$('#details').classList.remove('hidden');$('#details').querySelectorAll('[data-source]').forEach(x=>x.onclick=()=>play(x.dataset.source,x.dataset.title));$('#details').querySelector('[data-back]').onclick=closeDetails;state.focus=0;rebuildFocus()}
function closeDetails(){$('#details').classList.add('hidden');state.mode='home';state.focus=0;rebuildFocus()}
function avAvailable(){return typeof webapis!=='undefined'&&webapis.avplay}
async function play(url,title){state.mode='player';state.player={url,title,html:false};$('#playerTitle').textContent=title||'Воспроизведение';$('#player').classList.remove('hidden');try{if(avAvailable()){const p=webapis.avplay;try{p.close()}catch(_){ }p.open(url);p.setDisplayRect(0,0,1920,1080);p.setDisplayMethod('PLAYER_DISPLAY_MODE_LETTER_BOX');p.setListener({onbufferingstart:()=>toast('Буферизация…'),onbufferingcomplete:()=>{},oncurrentplaytime:t=>updateProgress(t,p.getDuration()),onstreamcompleted:()=>stopPlayer(true),onerror:e=>fallbackVideo(url,e)});p.prepareAsync(()=>{p.play();restoreProgress(url,p)},e=>fallbackVideo(url,e))}else fallbackVideo(url)}catch(e){fallbackVideo(url,e)}}
async function restoreProgress(url,p){try{const x=await api('/api/progress?source_url='+encodeURIComponent(url));if(x.position_ms>15000&&x.completed!==1)p.seekTo(x.position_ms)}catch(_){}}
function fallbackVideo(url,why){console.warn('AVPlay fallback',why);state.player.html=true;const v=$('#htmlVideo');v.src=url;v.classList.remove('hidden');v.play().catch(()=>toast('Формат не поддерживается телевизором'));v.ontimeupdate=()=>updateProgress(v.currentTime*1000,v.duration*1000);v.onended=()=>stopPlayer(true)}
function updateProgress(pos,dur){const pct=dur?Math.max(0,Math.min(100,pos/dur*100)):0;$('#playerProgress').style.width=pct+'%';if(!state.saveTimer){state.saveTimer=setTimeout(()=>{state.saveTimer=null;saveProgress(pos,dur,pct>95)},5000)}}
function saveProgress(pos,dur,completed){if(!state.player)return;fetch(API_BASE+'/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_url:state.player.url,position_ms:Math.round(pos||0),duration_ms:Math.round(dur||0),completed:!!completed})}).catch(()=>{})}
function playerToggle(){if(!state.player)return;if(state.player.html){const v=$('#htmlVideo');v.paused?v.play():v.pause();return}try{const p=webapis.avplay;p.getState()==='PLAYING'?p.pause():p.play()}catch(_){}}
function seek(delta){if(!state.player)return;if(state.player.html){const v=$('#htmlVideo');v.currentTime=Math.max(0,v.currentTime+delta/1000);return}try{const p=webapis.avplay;delta>0?p.jumpForward(delta):p.jumpBackward(Math.abs(delta))}catch(_){} }
function stopPlayer(completed){if(!state.player)return;let pos=0,dur=0;try{if(state.player.html){const v=$('#htmlVideo');pos=v.currentTime*1000;dur=v.duration*1000;v.pause();v.removeAttribute('src');v.load()}else{const p=webapis.avplay;pos=p.getCurrentTime();dur=p.getDuration();p.stop();p.close()}}catch(_){ }saveProgress(pos,dur,completed);$('#player').classList.add('hidden');state.player=null;state.mode='details';rebuildFocus()}
function move(dir){if(!state.focusables.length)return;const cur=state.focusables[state.focus];const r=cur.getBoundingClientRect();let best=state.focus,bestScore=Infinity;state.focusables.forEach((el,i)=>{if(i===state.focus)return;const x=el.getBoundingClientRect();const dx=(x.left+x.right-r.left-r.right)/2,dy=(x.top+x.bottom-r.top-r.bottom)/2;if((dir==='left'&&dx>=0)||(dir==='right'&&dx<=0)||(dir==='up'&&dy>=0)||(dir==='down'&&dy<=0))return;const primary=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy);const cross=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx);const score=primary+cross*2.4;if(score<bestScore){bestScore=score;best=i}});state.focus=best;rebuildFocus()}
function activate(){const el=state.focusables[state.focus];if(el)el.click()}
function registerKeys(){try{if(typeof tizen!=='undefined'&&tizen.tvinputdevice)tizen.tvinputdevice.registerKeyBatch(['MediaPlayPause','MediaPlay','MediaPause','MediaFastForward','MediaRewind'])}catch(e){console.warn(e)}}
function key(e){if(state.mode==='player'){if([13,10252].includes(e.keyCode)){playerToggle();return}if(e.keyCode===37||e.keyCode===412){seek(-10000);return}if(e.keyCode===39||e.keyCode===417){seek(10000);return}if([10009,27].includes(e.keyCode)){stopPlayer(false);return}}if(e.keyCode===37)move('left');else if(e.keyCode===38)move('up');else if(e.keyCode===39)move('right');else if(e.keyCode===40)move('down');else if(e.keyCode===13)activate();else if([10009,27].includes(e.keyCode)){if(state.mode==='details')closeDetails()}}
document.addEventListener('keydown',key);document.addEventListener('click',e=>{const f=e.target.closest('.focusable');if(f){const i=state.focusables.indexOf(f);if(i>=0){state.focus=i;rebuildFocus()}}});registerKeys();setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})},1000);load();
})();
